# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
